services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PeerNissen\SmtpFinisher\:
    resource: '../Classes/*'

  PeerNissen\SmtpFinisher\Domain\Finishers\SmtpFinisher:
    public: true
