services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PeerNissen\SmtpFinisher\:
    resource: '../Classes/*'

  PeerNissen\SmtpFinisher\Domain\Finishers\SmtpFinisher:
    public: true

  PeerNissen\SmtpFinisher\EventListener\DataStructureIdentifierListener:
    tags:
      - name: event.listener
        identifier: 'smtp-finisher/modify-data-structure'
        method: 'modifyDataStructure'